### PR TITLE
Add launch script for debugging

### PR DESCRIPTION
**Pull request by Acid147**

### CODE REVIEW

**Comment by 0x9ef** [comment]
Currently, V does not have a debugger as such. Before configuring the scripts need to write an adapter to this debugger (which also is not).

**Comment by Acid147** [comment]
Not sure if I understand what you mean.

The script is for debugging the extension and not V code, if that's what you're referring to.

**Comment by 0x9ef** [comment]
Oh... Really :) Sorry for my incompetence.

**Comment by Acid147** [comment]
It's alright :)

**Pull request merged**
