### PR TITLE
Create TypeScript project

### PR DESCRIPTION
**Pull request by Acid147**
I have created a basic TypeScript project for the extension with (empty) functions that get executed when any of the commands (like `v.run`) are executed.

### CODE REVIEW

**Comment by 0x9ef** [comment]
I have some troubles with testing. I dont know anything about TypeScript extension. If im try to build extension, im getting:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'vscode:prepublish' ]
2 info using npm@6.9.0
3 info using node@v10.16.0
4 verbose run-script [ 'prevscode:prepublish',
4 verbose run-script   'vscode:prepublish',
4 verbose run-script   'postvscode:prepublish' ]
5 info lifecycle vscode-vlang@0.0.4~prevscode:prepublish: vscode-vlang@0.0.4
6 info lifecycle vscode-vlang@0.0.4~vscode:prepublish: vscode-vlang@0.0.4
7 verbose lifecycle vscode-vlang@0.0.4~vscode:prepublish: unsafe-perm in lifecycle true
8 verbose lifecycle vscode-vlang@0.0.4~vscode:prepublish: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;E:\vscode-vlang\vscode-vlang\node_modules\.bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;D:\Python27\;D:\Python27\Scripts;D:\Python37\Scripts\;D:\Python37\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\Git\cmd;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;D:\Go\bin;C:\Program Files (x86)\Visual Leak Detector\bin\Win32;C:\Program Files (x86)\Visual Leak Detector\bin\Win64;C:\Program Files\nodejs;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;%SystemRoot%\system32;%SystemRoot%;%SystemRoot%\System32\Wbem;%SYSTEMROOT%\System32\WindowsPowerShell\v1.0\;%SYSTEMROOT%\System32\OpenSSH\;E:\Visual Studio\Tools\VC\Tools\MSVC\14.16.27023\bin\Hostx86\x86;D:\Nmap;E:\LLVM\bin;E:\xampp\php;C:\;C:\Users\Paparoni\AppData\Roaming\npm;C:\Users\Paparoni\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\mingw-w64\x86_64-8.1.0-posix-seh-rt_v6-rev0\mingw64\bin;C:\Users\Paparoni\AppData\Local\Microsoft\WindowsApps
9 verbose lifecycle vscode-vlang@0.0.4~vscode:prepublish: CWD: E:\vscode-vlang\vscode-vlang
10 silly lifecycle vscode-vlang@0.0.4~vscode:prepublish: Args: [ '/d /s /c', 'npm run compile' ]
11 silly lifecycle vscode-vlang@0.0.4~vscode:prepublish: Returned: code: 1  signal: null
12 info lifecycle vscode-vlang@0.0.4~vscode:prepublish: Failed to exec vscode:prepublish script
13 verbose stack Error: vscode-vlang@0.0.4 vscode:prepublish: `npm run compile`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid vscode-vlang@0.0.4
15 verbose cwd E:\vscode-vlang\vscode-vlang
16 verbose Windows_NT 10.0.18362
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "vscode:prepublish"
18 verbose node v10.16.0
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 1
22 error vscode-vlang@0.0.4 vscode:prepublish: `npm run compile`
22 error Exit status 1
23 error Failed at the vscode-vlang@0.0.4 vscode:prepublish script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

```
Can you explain me where is the problem?
And update dependency from `~1.35.0` to `~1.26.0`.

**Comment by Acid147** [comment]
Which command did you use to build it? `npm run compile`? I don't get an error for any of the commands, maybe if I test it using Windows.

> And update dependency from ~1.35.0 to ~1.26.0.

Sure, I'll change that.

**Comment by Acid147** [comment]
It seems like the postinstall script was an issue. Can you try again with my new commit?

**Comment by 0x9ef** [comment]
Oh, had to do `npm install` for build this package :)

**Pull request merged**
